### ISSUE TITLE
Travis job is not started: fix or migrate to Actions?

### ISSUE THREAD

**Issue by JeroenVanOort** [timeweb/phpstan-enum#16]
I was working on https://github.com/timeweb/phpstan-enum/pull/15 and I noticed that no Travis job is started. Is this something to be fixed or should a move be made towards Github Actions?

**Comment by Yozhef** [comment]
Hello everybody. Guys, tell me about your next plans to support this repository?
Maybe if you need help I can help you update this repository?

**Comment by Yozhef** [comment]
@rincler @samizdam @bottleneko Hello everybody. Guys, tell me about your next plans to support this repository?
Maybe if you need help I can help you update this repository?

**Comment by rincler** [comment]
Hi! I support this repo. 
I've released changes for compatibility of php 8, but I did not pay attention to broken tests, so I've marked last release as YANKED. It seems to need to update phpunit dependency. I will resolve problems at this in the near future.

**Comment by Yozhef** [comment]
@rincler How do you feel about making some changes?:

1. Code style
2. Code style check
3. PHPStan
4. Change Travis to GitHub action

I can help you with that.
