### ISSUE TITLE
Class Timeweb\PHPStan\Rule\EnumAlwaysUsedConstants not found.

### ISSUE THREAD

**Issue by burned42** [timeweb/phpstan-enum#20]
After updating from 2.2.4 to 2.3.0 I got this exception when running phpstan:

> In Resolver.php line 110:
>     Service '0366': Class Timeweb\PHPStan\Rule\EnumAlwaysUsedConstants not found.  

The mentioned class does indeed not exist, but there's a class `Timeweb\PHPStan\Rule\EnumAlwaysUsedConstantsExtension` (introduced in https://github.com/timeweb/phpstan-enum/pull/18). When adjusting the class name in `extension.neon` phpstan runs fine.

**Comment by shadowhand** [comment]
Same issue here, and this is a minor version change that should not be breaking BC.

**Comment by samizdam** [comment]
Thank you for fix! 

Use v2.3.1, please.
