### ISSUE TITLE
PHPStan 2.0 compatibility

### ISSUE THREAD

**Issue by devnix** [timeweb/phpstan-enum#36]
Hi! PHPStan 2.0 was released recently, here's the migration guide for it: https://github.com/phpstan/phpstan/blob/2.0.x/UPGRADING.md#upgrading-guide-for-extension-developers

I can try to look at it, but I don't have any previous experience developing PHPStan plugins.

**Comment by jdecool** [comment]
Sure a PR has been started (https://github.com/timeweb/phpstan-enum/pull/35) and will be merged soon.

**Comment by jdecool** [comment]
The PR has just been merged and a new tag (4.0.0) has been created.

**Comment by devnix** [comment]
Thank you!
